name: Autograding using Poetry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      if: ${{ github.actor != 'github-classroom[bot]' }}

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
      if: ${{ github.actor != 'github-classroom[bot]' }}

    - name: Install dependencies
      run: |
        poetry install
      if: ${{ github.actor != 'github-classroom[bot]' }}

    - name: Test with pytest
      run: |
        poetry run pytest
      if: ${{ github.actor != 'github-classroom[bot]' }}
